[package]
name = "toml_benchmarks"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[package.metadata.release]
release = false

[dependencies]
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
tomlini = { path = "../tomlini" }
tomlini_serde = { path = "../tomlini_serde" }
divan = "0.1"

[[bench]]
name = "3-edit"
harness = false

[[bench]]
name = "6-serde"
harness = false

[[bench]]
name = "7-ini"
harness = false

[[bench]]
name = "8-realworld"
harness = false

[lints]
workspace = true
