[package]
name = "tomlini_serde"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false
description = "Serde Deserializer powered by tomlini's flat-span parser"

[package.metadata.release]
release = false

[dependencies]
tomlini = { path = "../tomlini", default-features = false, features = ["alloc"] }
serde.workspace = true
toml_datetime = { workspace = true, features = ["serde"] }
[features]
default = ["std"]
std = ["alloc", "tomlini/std"]
alloc = ["tomlini/alloc"]
[dev-dependencies]
serde = { version = "1", features = ["derive"] }
tomlini = { path = "../tomlini" }

[lints]
workspace = true
