[package]
name = "tomlini_serde"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false
description = "Serde Deserializer powered by tomlini's flat-span parser"

[package.metadata.release]
release = false

[dependencies]
tomlini = { path = "../tomlini", default-features = false }
serde = { version = "1", default-features = false, features = ["derive"] }

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
tomlini = { path = "../tomlini" }

[lints]
workspace = true
